# .rubocop.yml

##
# This is the RuboCop configuration file.
# It contains the rules and settings for the RuboCop linter.
#
# Enable/disable the cops individually. For more information,
# refer to the RuboCop documentation:
# https://docs.rubocop.org/rubocop/cops.html
#
plugins:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  UseCache: true
  MaxFilesInCache: 100
  TargetRubyVersion: 3.4
  Exclude:
    - "spec/**/*"
    - "vendor/**/*"

#
# Trailing commas
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true

Style/TrailingCommaInBlockArgs:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Gemspec/DevelopmentDependencies:
  Enabled: true

Layout/HashAlignment:
  Enabled: false

Lint/Void:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
  Max: 20

Metrics/ClassLength:
  Enabled: true
  Max: 200

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Max: 40
  CountAsOne: ["method_call"]

Metrics/ModuleLength:
  Enabled: true
  Max: 250
  CountAsOne: ["method_call"]

Performance/Size:
  Enabled: true
  Exclude:
  #   - lib/example.rb

Style/NegatedIfElseCondition:
  Enabled: true

Naming/AsciiIdentifiers:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

# We use class instance vars sparingly at load time
ThreadSafety/ClassInstanceVariable:
  Enabled: false
