# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{otto}
  s.version = "0.2.1.002"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Delano Mandelbaum"]
  s.date = %q{2011-07-07}
  s.description = %q{Auto-define your rack-apps in plaintext.}
  s.email = %q{delano@solutious.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
     "README.md"
  ]
  s.files = [
    "CHANGES.txt",
     "LICENSE.txt",
     "README.md",
     "Rakefile",
     "VERSION.yml",
     "lib/otto.rb",
     "otto.gemspec"
  ]
  s.homepage = %q{http://github.com/delano/otto}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{otto}
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Auto-define your rack-apps in plaintext.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack>, [">= 1.2.1"])
      s.add_runtime_dependency(%q<addressable>, ["= 2.2.4"])
    else
      s.add_dependency(%q<rack>, [">= 1.2.1"])
      s.add_dependency(%q<addressable>, ["= 2.2.4"])
    end
  else
    s.add_dependency(%q<rack>, [">= 1.2.1"])
    s.add_dependency(%q<addressable>, ["= 2.2.4"])
  end
end

