name: CI

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    name: "RSpec Tests (Ruby ${{ matrix.ruby }})"
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - ruby: "3.2"
            experimental: false
          - ruby: "3.3"
            experimental: false
          - ruby: "3.4"
            experimental: false
          - ruby: "3.5"
            experimental: true

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run RSpec tests
        run: bundle exec rspec
